/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Gloriana
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public PrincipalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAlgoritmoGenetico = new javax.swing.JLabel();
        lblTamPoblacion = new javax.swing.JLabel();
        txtTamPoblacion = new javax.swing.JTextField();
        lblProbabilidadCruce = new javax.swing.JLabel();
        txtProbabilidadCruce = new javax.swing.JTextField();
        lblPorcentajeGenes = new javax.swing.JLabel();
        txtPorcentajeGenes = new javax.swing.JTextField();
        lblPorcentajeIndividuosMenosAptos = new javax.swing.JLabel();
        txtPorcentajeIndividuosMenosAptos = new javax.swing.JTextField();
        lblRutaImagenMeta = new javax.swing.JLabel();
        txtRutaImagenMeta = new javax.swing.JTextField();
        btnIngresarDatos = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        comboBoxAlgoritmo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblRutaImagenDestino = new javax.swing.JLabel();
        txtRutaImagenDestino = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        lblAlgoritmoGenetico.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lblAlgoritmoGenetico.setText("Algoritmo genético");

        lblTamPoblacion.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblTamPoblacion.setText("Tamaño de la población");

        txtTamPoblacion.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txtTamPoblacion.setToolTipText("tamaño población");
        txtTamPoblacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamPoblacionActionPerformed(evt);
            }
        });

        lblProbabilidadCruce.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblProbabilidadCruce.setText("Probabilidad de cruce entre dos individuos");

        txtProbabilidadCruce.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        lblPorcentajeGenes.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblPorcentajeGenes.setText("Porcentaje de genes a mutar");

        txtPorcentajeGenes.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        lblPorcentajeIndividuosMenosAptos.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblPorcentajeIndividuosMenosAptos.setText("Porcentaje individuos menos aptos a mantener");

        txtPorcentajeIndividuosMenosAptos.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        lblRutaImagenMeta.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblRutaImagenMeta.setText("Ruta de la imagen meta");

        txtRutaImagenMeta.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        btnIngresarDatos.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresarDatos.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnIngresarDatos.setText("Ingresar datos");
        btnIngresarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarDatosActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        comboBoxAlgoritmo.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        comboBoxAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distancia euclideana", "Manhattan", "Filtrado de imágenes" }));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de algoritmo");

        lblRutaImagenDestino.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblRutaImagenDestino.setText("Ruta de la imagen destino");

        txtRutaImagenDestino.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIngresarDatos)
                .addGap(268, 268, 268)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(lblAlgoritmoGenetico))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProbabilidadCruce)
                            .addComponent(lblPorcentajeIndividuosMenosAptos)
                            .addComponent(lblTamPoblacion)
                            .addComponent(lblPorcentajeGenes)
                            .addComponent(lblRutaImagenMeta)
                            .addComponent(jLabel1)
                            .addComponent(lblRutaImagenDestino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPorcentajeGenes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPorcentajeIndividuosMenosAptos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboBoxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProbabilidadCruce, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTamPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRutaImagenMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRutaImagenDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(317, 317, 317))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlgoritmoGenetico)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamPoblacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProbabilidadCruce, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProbabilidadCruce))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPorcentajeGenes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentajeGenes))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPorcentajeIndividuosMenosAptos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentajeIndividuosMenosAptos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaImagenMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRutaImagenMeta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaImagenDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRutaImagenDestino))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarDatosActionPerformed

    private void txtTamPoblacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamPoblacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamPoblacionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnIngresarDatos;
    public javax.swing.JComboBox<String> comboBoxAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlgoritmoGenetico;
    private javax.swing.JLabel lblPorcentajeGenes;
    private javax.swing.JLabel lblPorcentajeIndividuosMenosAptos;
    private javax.swing.JLabel lblProbabilidadCruce;
    private javax.swing.JLabel lblRutaImagenDestino;
    private javax.swing.JLabel lblRutaImagenMeta;
    private javax.swing.JLabel lblTamPoblacion;
    public javax.swing.JTextField txtPorcentajeGenes;
    public javax.swing.JTextField txtPorcentajeIndividuosMenosAptos;
    public javax.swing.JTextField txtProbabilidadCruce;
    public javax.swing.JTextField txtRutaImagenDestino;
    public javax.swing.JTextField txtRutaImagenMeta;
    public javax.swing.JTextField txtTamPoblacion;
    // End of variables declaration//GEN-END:variables
    
    public boolean principalDatosCorrectos(){
        //Método que verifica que los textFields no estén vacíos
        return !txtPorcentajeGenes.getText().equals("") && !txtPorcentajeIndividuosMenosAptos.getText().equals("") && !txtProbabilidadCruce.getText().equals("") && !txtRutaImagenMeta.getText().equals("") && !txtTamPoblacion.getText().equals("") && !txtRutaImagenDestino.getText().equals("");
    }
    
    
    public void cerrarVentana(){
        System.exit(0);
    }


}
